name: Handle Issue Checkbox Updates

on:
  issues:
    types: [edited]

jobs:
  process-checkboxes:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.12.0"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub==2.6.1

      - name: Process checked items
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_TITLE: "Check Dirty-Waters Updates"
        run: |
          python .github/scripts/process_checkboxes.py
