name: Track Dirty-Waters Tags

on:
  schedule:
    - cron: "0 */6 * * *" # Run every 6 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  update-tracking-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.12.0"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub==2.6.1 requests==2.32.3

      - name: Update tracking issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_TITLE: "Check Dirty-Waters Updates"
          SOURCE_REPO: "chains-project/dirty-waters"
          ACTION_REPO: "randomicecube/issue-sandbox"
        run: |
          python .github/scripts/update_tracking_issue.py
